name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

jobs:
  depot-cacheless:
    name: Depot Cacheless
    runs-on:
      size: 2x8
      image: ${{ vars.BENCHMARK_SNAPSHOT_IMAGE }}
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: false
      - run: |
          rm /home/runner/.bazelrc
          bazel build :grpc

  depot-remote-cache:
    name: Depot with Remote Cache
    runs-on:
      size: 2x8
      image: ${{ vars.BENCHMARK_SNAPSHOT_IMAGE }}
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: false
      - run: bazel build :grpc
